server:
  port: 9001
spring:
  data:
    mongodb:
      # 集群配置：mongodb://user:pwd@ip1:port1,ip2:port2/database
#      uri: mongodb://test:test@localhost:27017/test
      database: Test
      host: 127.0.0.1
#      username: test
#      password: test
      port: 27017
